dist: bionic
os: linux
sudo: required
language: cpp
compiler: g++
before_install:
  - sudo apt-get -y install libgl1-mesa-dev
  - sudo apt-get -y install libopenal-dev
  - sudo apt-get -y install libjpeg-dev
  - sudo apt-get -y install libudev-dev
  - sudo apt-get -y install libxrandr-dev
  - sudo apt-get -y install libfreetype6-dev
  - sudo apt-get -y install libvorbis-dev
  - sudo apt-get -y install libflac-dev
  - echo 'deb http://ftp.de.debian.org/debian sid main' |sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com `sudo apt-get update 2>&1 | grep -o '[0-9A-Z]\{16\}$' | xargs`
  - sudo apt-get -y install libsfml-audio2.5
script:
- make && make run && make testing
- git ls-files src/ | xargs clang-format -i && git diff --exit-code