dist: xenial
sudo: required
language: cpp
compiler: g++
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    update: true
before_install:
  - sudo apt-get -y install g++
script:
- make && make run && make testing
- git ls-files src/ | xargs clang-format -i && git diff --exit-code