dist: bionic
os: linux
sudo: required
language: cpp
compiler: g++
before_install:
  - sudo apt-get -y install libsfml-dev
script:
- make
- git ls-files src/ | xargs clang-format -i && git diff --exit-code