dist: xenial
sudo: required
language: cpp
compiler: g++
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsfml-dev
script:
- make && make run && make testing
- git ls-files src/ | xargs clang-format -i && git diff --exit-code