dist: xenial
sudo: required
language: cpp
compiler: g++
addons:
  apt:
    packages:
    - libsfml-dev
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - lsfml-audio
    update: true
script:
- make && make run && make testing
- git ls-files src/ | xargs clang-format -i && git diff --exit-code